DWAPlannerROS:
  max_vel_x: 1.5
  min_vel_x: -1.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  recovery_behavior_enabled: false
  clearing_rotation_allowed: false
  planner_frequency: 0
  holonomic_robot: true
